version: '3'

services:
  db:
    image: mongo:latest
    env_file:
      - ./.env.dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c "cd root/app && 
        python manage.py makemigrations &&
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    volumes:
      - ./app:/root/app
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  mongodb_data_container:

