version: '3'

services:
  db:
    image: mongo:latest
    env_file:
      - ./.env.dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  web:
    build: .
    command: python /root/app/manage.py runserver 0:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./app:/root/app
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  mongodb_data_container:


# docker-compose exec web pytest