version: '3'

services:
  db:
    image: mongo:latest
    env_file:
      - ./.env.prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: > 
        bash -c "cd root/app && cat manage.py && ls -la && env &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn mysite.wsgi --bind 0.0.0.0:8000"
    env_file:
      - ./.env.prod
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  mongodb_data_container:
